config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  root to: 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :post_tag_relations
  has_many :tags, through: :post_tag_relations

  validates :text, presence: true, length: { maximum: 300 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:edit, :update ,:destroy, :show]

  def index
    @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
    @posts = @posts.includes(:user).order(updated_at: "DESC", id: "DESC").page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path, alert: "投稿が完了しました"
    else
      render :new
    end
  end

  def show
    @comments = @post.comments.includes(:user).order(updated_at: "DESC", id: "DESC")
    @comment = Comment.new ###current_user.comments.new
    # @like = Like.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_url, flash: { alert: '編集が完了しました' }
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:alert] = "削除が完了しました"
    redirect_to posts_url  ## root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text, tag_ids: []).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post, local: true, html: { class: "form_area" } do |f| %>
  <div class="form_area__field">
    <%= render 'layouts/error_messages',  model: f.object %>
    <%= f.text_area :text, id: "post_text", placeholder: "投稿内容を入力", autofocus: "autofocus", rows: 10 %>
      <div class="form_area__hidden_field">
        <%= hidden_field :post, :user_id, value: current_user.id %>
      </div>

  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>


      <div class="form_area__action">
        <%= f.submit "保存", class: "form_area__action__btn" %>
      </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="post_wrapper">
<% breadcrumb :edit_post, @post %>
<%= render 'layouts/breadcrumbs' %>
  <div class="post_wrapper__content">
    <div class="post_wrapper__content__post_form">
      <h3 class="text-center">
        <span class="h3">投稿編集</span>
      </h3>
      <%= render partial: 'form', locals: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="post_wrapper">
  <div class="post_wrapper__header">
    <h3 class="title">
      <span class="h3">投稿一覧</span>
    </h3>
  </div>
  <%= form_tag posts_path, method: :get, class: 'post_wrapper__content__posts__searchForm' do %>
    <%= select_tag :tag_id,
                  options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                  {
                    prompt: 'タグで絞り込み',
                    class: 'form-control posts__select',
                    onchange: 'submit(this.form);'
                  }
    %>
  <% end %>
  <div class="post_wrapper__content">
    <ul class="post_wrapper__content__post_list">
      <% if @posts.blank? %>
        <h3><span>まだ投稿されたスレッドはありません。</span></h3>
      <% else %>
        <% @posts.each do |post| %>
        <%= link_to post_path(post), method: :get do %>
          <li>
          <div class="post">
            <div class="post__top_box">
              <div class="post__top_box__name">
                <span>投稿者：<span class="text-primary"><%= post.user.name %></span></span>
              </div>
              <div class="post__top_box__time">
                <span>投稿日時：<%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
              </div>
            </div>
            <div class="post__index_tag">
              <% post.tags.each do |tag| %>
                <span class="badge badge-primary"><%= tag.name %></span>
              <% end %>
            </div>
            <div class="post__middle_box">
              <span><%= markdown(post.text).html_safe %></span>
            </div>
            <div class="post__bottom_box">
              <ul class="post__bottom_box__user_actions">
                <li>
                  <i class="far fa-comment-alt"></i>
                  <span><%= post.comments.count %>&nbsp;件</span>
                </li>
                <li>
                <% if user_signed_in? && current_user.already_liked?(post) %>
                  <%= link_to post_like_path(id: post.id, post_id: post.id), class: "post_action_btn post_liked", method: :delete do %>
                    <%# <i class="far fa-heart"></i> %>
                    <i class="fas fa-thumbs-up"></i>
                      <span><%= post.likes.count %>&nbsp;イイね！</span>
                  <% end %>
                <% else %>
                  <%= link_to post_likes_path(post), class: "post_action_btn", method: :post do %>
                    <i class="far fa-thumbs-up"></i>
                      <span><%= post.likes.count %>&nbsp;イイね！</span>
                  <% end %>
                <% end %>
                </li>
              </ul>
              <ul class="post__bottom_box__admin_actions">
                <% if user_signed_in? && current_user.id == post.user_id %>
                  <li><%= link_to '編集', edit_post_path(post.id) %></li>
                  <li><%= link_to '削除', post_path(post.id), method: :delete, data: { confirm: "本当に削除して良いですか？", cancel: "やめる", commit: "削除する" }, title: "削除確認" %></li>
                <% end %>
              </ul>
            </div>
          </div>
          </li>
        <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<div class="post_wrapper">
<% breadcrumb :new_post %>
<%= render 'layouts/breadcrumbs' %>
  <div class="post_wrapper__content">
    <div class="post_wrapper__content__post_form">
      <h3 class="text-center">
        <span class="h3">新規投稿</span>
      </h3>
      <%= render partial: 'form', locals: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post_wrapper">
<% breadcrumb :show_post, @post %>
<%= render 'layouts/breadcrumbs' %>
  <div class="post_wrapper__header">
    <h3 class="title">
      <span class="h3">投稿詳細</span>
    </h3>
    <div class="back_link">
      <%= link_to root_path do %>
        <i class="fas fa-angle-double-left"></i>
        <span>一覧へ戻る</span>
      <% end %>
    </div>
  </div>
  <div class="post_wrapper__content scroll">
    <div class="post_wrapper__content__post_show">
      <div class="post_detail">
        <div class="post_detail__top_box">
          <div class="post_detail__top_box__name">
            <span>投稿者：<span class="text-primary"><%= @post.user.name %></span></span>
          </div>
          <div class="post_detail__top_box__name">
            <span>投稿日時： <%= @post.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
          </div>
        </div>
        <% @post.tags.each do |tag| %>
          <span class="badge badge-primary"><%= tag.name %></span>
        <% end %>

        <div class="post_detail__middle_box">
          <span><%= markdown(@post.text).html_safe %></span>
        </div>
        <div class="post_detail__bottom_box">
          <ul class="post_detail__bottom_box__user_actions">
            <li>
              <i class="far fa-comment-alt"></i>
              <span><%= @post.comments.count %>&nbsp;件</span>
            </li>
            <li>
                <% if user_signed_in? && current_user.already_liked?(@post) %>
                  <%= link_to post_like_path(id: @post.id, post_id: @post.id), class: "post_action_btn post_liked", method: :delete do %>
                    <i class="fas fa-thumbs-up"></i>
                      <span><%= @post.likes.count %>&nbsp;イイね！</span>
                  <% end %>
                <% else %>
                  <%= link_to post_likes_path(@post), class: "post_action_btn", method: :post do %>
                    <i class="far fa-thumbs-up"></i>
                      <span><%= @post.likes.count %>&nbsp;イイね！</span>
                  <% end %>
                <% end %>
              <%# <i class="far fa-heart"></i>
              <span>いいね数</span> %>
            </li>
          </ul>
          <div class="post_detail__bottom_box__admin_actions">
          <% if user_signed_in? && current_user.id == @post.user_id %>
            <%= link_to '編集', edit_post_path(@post.id), method: :get %>
            <%= link_to '削除', post_path(@post.id), method: :delete, data: { confirm: "本当に削除して良いですか？", cancel: "やめる", commit: "削除する" }, title: "削除確認" %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="comment_area">
      <ul class="comment_area__list">
        <%# コメントがある場合は、全てのコメントが表示されていること %>
        <% if @comments.present? %>
          <% @comments.each do |comment| %>
            <li class="comment_area__list__comment">
              <div class="comment_area__list__comment__left_box">
                <span><%= comment.user.name %></span>
              </div>
              <div class="comment_area__list__comment__right_box">
                <div class="comment_area__list__comment__right_box__info">
                  <% if user_signed_in? && current_user.id == comment.user_id %>
                    <span><%= link_to "編集", edit_post_comment_path(@post.id, comment.id), method: :get %></span>
                    <span><%= link_to "削除", post_comment_path(@post.id, comment.id), method: :delete, data: { confirm: "本当に削除して良いですか？", cancel: "やめる", commit: "削除する" }, title: "削除確認"  %></span>
                  <% end %>
                  <span>投稿日時：<%= comment.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
                </div>
                <div class="comment_area__list__comment__right_box__text">
                  <span><%= comment.text %></span>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
      <%# コメントのフォームを設置 %>
        <% if user_signed_in? %>
          <div class="comment_area__form_box">
            <%= form_with model: [@post, @comment], class: 'comment_area__form_box__form', local: true do |f| %>
              <div class="comment_area__form_box__form__field">
                <%= render 'layouts/error_messages',  model: f.object %>
                <%= f.text_area :text, id: "comment_text", placeholder: "コメントを入力", autofocus: "autofocus", rows: 2 %>
              </div>
              <div class="comment_area__form_box__form__hidden_field">
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: @post.id %>
              </div>
              <div class="comment_area__form_box__form__action">
                <%= f.submit "送信", class: "comment_area__form_box__form__action__btn" %>
              </div>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>