config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  root to: 'posts#index'
end

app/views/layouts/_breadcrumbs.html.erb
<%# パンくずリストのテンプレートファイル %>
<div class="breadcrumbs">
  <div class="home_icon">
    <i class="fas fa-home"></i>
  </div>
    <%= breadcrumbs separator: "&nbsp; &raquo; &nbsp;", class: "breadcrumbs-list" %>
</div>

app/views/layouts/_error_messages.html.erb
  <% if model.errors.any? %>
    <div class="vali_alert">
      <ul>
        <% model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer__bar">
    <h4 class="footer__bar__icon">
    <%= link_to root_path do %>
      <span>掲示板アプリ</span>
    <% end %>
    </h4>
    <div class="footer__bar__copylight">
      <span>©2021 yosyos All Rights Reserved.</span>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header__bar">
    <h1>
      <%= link_to root_path do %>
      <%= image_tag 'favicon.ico', :size => '80x70' %>
        <span>掲示板アプリ</span>
      <% end %>
    </h1>
    <% if user_signed_in? %>
      <ul class="header__bar__user_nav">
        <li class="user_name">
          <span><%= current_user.name %>さん</span>
        </li>
        <li class="header__bar__user_nav__btn">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        </li>
        <li class="header__bar__user_nav__btn">
          <%= link_to '投稿する', new_post_path, method: :get %>
        </li>
      </ul>
    <% else %>
      <ul class="header__bar__user_nav">
        <li class="header__bar__user_nav__btn">
          <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post %>
          <%# <span>ゲストログイン</span> %>
        </li>
        <li class="header__bar__user_nav__btn">
          <%= link_to 'ログイン', new_user_session_path, method: :get %>
        </li>
        <li class="header__bar__user_nav__btn">
          <%= link_to '新規登録', new_user_registration_path, method: :get %>
        </li>
      </ul>
    <% end %>
  </div>
</header>

app/views/layouts/_notifications.html.erb
<%# フラッシュメッセージのテンプレートファイル %>
<div class="notifications">
  <% flash.each do |message_type, message| %>
    <div class="message_type text-center <%= message_type %> alert-<%= message_type %>">
    <%### alert-でflashのkeyを呼び出す、redirect_to noticeの時はこれは不要 %>
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/notifications' %>
      <div class="wrapper">
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
  </body>
</html>